### ISSUE TITLE
How to get active ammo using c#?

### ISSUE THREAD

**Issue by josealissonbr** [GaryFrazier/RE4MP#1]
Hello friend, I'm trying to learn how to make a mod for Resident evil 4, and I'm having difficulties getting the ammo value of the current weapon, could you help me?

**Comment by Grep5268** [comment]
Hi! Of course, do you have a discord?

**Comment by josealissonbr** [comment]
i don't have :(

**Comment by josealissonbr** [comment]
You can talk to me here.

**Comment by Grep5268** [comment]
Ok, so which part do you have trouble with, just finding the value in cheat engine?

**Comment by Jay184** [comment]
Current Ammo is saved in `[bio4.exe+86D760]+8` as an 2 byte integer. The integer is multiplied by 8 so dividing by 8 gives the correct ammo count.

To do this in C#, use the two functions `OpenProcess` and `ReadProcessMemory` in the kernel32.dll via PInvokes:
```csharp
[DllImport("kernel32.dll", SetLastError = true)]
static extern IntPtr OpenProcess(ProcessAccessFlags dwDesiredAccess, bool bInheritHandle, int dwProcessId);
```
and
```csharp
[DllImport("kernel32.dll", SetLastError = true)]
static extern bool ReadProcessMemory(IntPtr hProcess, IntPtr lpBaseAddress, [Out] byte[] lpBuffer, int dwSize, out int dwNumberOfBytesRead);
```
Hint: You should also use `CloseHandle` when exiting the application.

PseudoCode:
```csharp
Process process = Process.GetProcessesByName("bio4")[0];
int pid = process.id;
int handle = OpenProcess(ACCESS, false, pid);
int baseAddress = FindModule(process, "bio4.exe");
IntPtr address = ReadUInt32(handle, baseAddress + 0x86D760) + 8;
int ammo = ReadUInt16(handle, address) / 8;
```
